airflow:
  airflowVersion: "2.3.4"
  
  # For installing the chart using ArgoCD these variables should be set to false
  createUserJob:
    useHelmHooks: false

  migrateDatabaseJob:
    useHelmHooks: false
